package com.datajpa.springdatajpa.model;

public enum Department {
    INFORMATION_TECHNOLOGY,
    COMPUTER_ENGINEERING,
    CIVIL_ENGINEERING,
    MECHANICAL_AUTOMATION_ENGINEERING,
    ELECTRICAL_ELECTRONICS_ENGINEERING,
    COMPUTER_SCIENCE,
    INSTRUMENTATION_SENSOR_ENGINEERING,
    ENVIRONMENTAL_ENGINEERING
}
